[
    { "id": 1, "name": "Костюм тройка Джозеф Глимко", "price": 51900, "image": "https://provokatorspb.ru/imgs/products_web/big/1766151847_4Fa.webp" },
    { "id": 2, "name": "Смокинг Никола Тоскано", "price": 58900, "image": "https://provokatorspb.ru/imgs/products_web/big/1770816543_g2N.webp" },
    { "id": 3, "name": "Смокинг Майкл Конти", "price": 58900, "image": "https://provokatorspb.ru/imgs/products_web/big/1770816421_c7g.webp" },
    { "id": 4, "name": "Костюм тройка Diffuzio Gariccio Wedding Black", "price": 29950, "image": "https://provokatorspb.ru/imgs/products_web/big/1770152163_DV3.webp" },
    { "id": 5, "name": "Костюм тройка Diffuzio Gariccio Black", "price": 29950, "image": "https://provokatorspb.ru/imgs/products_web/big/1770151760_P2O.webp" },
    { "id": 6, "name": "Костюм тройка Diffuzio Gariccio Wedding Blue", "price": 29950, "image": "https://provokatorspb.ru/imgs/products_web/big/1770151528_mpz.webp" },
    { "id": 7, "name": "Костюм тройка Diffuzio Gariccio Blue", "price": 29950, "image": "https://provokatorspb.ru/imgs/products_web/big/1770151107_2Kg.webp" },
    { "id": 8, "name": "Костюм тройка Diffuzio Gariccio Wedding Grey", "price": 29950, "image": "https://provokatorspb.ru/imgs/products_web/big/1770149620_nMB.webp" },
    { "id": 9, "name": "Костюм тройка Дон Сальери", "price": 52900, "image": "https://provokatorspb.ru/imgs/products_web/big/1767537050_bMp.webp" },
    { "id": 10, "name": "Костюм тройка Винсент Гиганте", "price": 56900, "image": "https://provokatorspb.ru/imgs/products_web/big/1767536868_KIV.webp" },
    { "id": 11, "name": "Костюм тройка Сант-Альбино", "price": 54900, "image": "https://provokatorspb.ru/imgs/products_web/big/1766151847_4Fa.webp" },
    { "id": 12, "name": "Костюм тройка Франк Костелло", "price": 55900, "image": "https://provokatorspb.ru/imgs/products_web/big/1766149033_xOJ.webp" },
    { "id": 13, "name": "Костюм тройка Сан-Винченцо", "price": 56900, "image": "https://provokatorspb.ru/imgs/products_web/big/1760329162_lcl.webp" },
    { "id": 14, "name": "Костюм тройка Пол Рикарди", "price": 56900, "image": "https://provokatorspb.ru/imgs/products_web/big/1760329013_pyQ.webp" },
    { "id": 15, "name": "#", "price": 3490, "image": "" },
    { "id": 16, "name": "#", "price": 6490, "image": "" },
    { "id": 17, "name": "Ботинки кожаные", "price": 11990, "image": "" },
    { "id": 18, "name": "Жилет стеганый", "price": 7990, "image": "" },
    { "id": 19, "name": "Джинсы mom-fit", "price": 6490, "image": "" },
    { "id": 20, "name": "Топ кружевной", "price": 3990, "image": "" },
    { "id": 21, "name": "Кардиган вязаный", "price": 7490, "image": "" },
    { "id": 22, "name": "Брюки палаццо", "price": 5990, "image": "" },
    { "id": 23, "name": "Куртка джинсовая", "price": 8990, "image": "" },
    { "id": 24, "name": "Сандалии летние", "price": 4990, "image": "" },
    { "id": 25, "name": "Комбинезон", "price": 9990, "image": "" },
    { "id": 26, "name": "Пиджак классический", "price": 11990, "image": "" },
    { "id": 27, "name": "Лонгслив", "price": 3990, "image": "" },
    { "id": 28, "name": "Юбка карандаш", "price": 4490, "image": "" },
    { "id": 29, "name": "Ветровка", "price": 7990, "image": "" },
    { "id": 30, "name": "Туфли на каблуке", "price": 8990, "image": "" },
    { "id": 31, "name": "Сарафан", "price": 5490, "image": "" },
    { "id": 32, "name": "Тренч", "price": 13990, "image": "" },
    { "id": 33, "name": "Брюки спортивные", "price": 4990, "image": "" },
    { "id": 34, "name": "Рубашка фланелевая", "price": 5490, "image": "" },
    { "id": 35, "name": "Ботильоны", "price": 10990, "image": "" },
    { "id": 36, "name": "Жакет", "price": 9990, "image": "" }
]